### ISSUE TITLE
Remove CBR comic book

### ISSUE THREAD

**Issue by hadess** [hadess/gnome-demo-content#4]
We don't have anything to unpack RARs in a default Fedora.

**Comment by Kekun** [comment]
What about using CBZ instead?

**Comment by hadess** [comment]
I'd rather not modify the file as it was downloaded and instead have distributions ship `unrar-free` for example:
https://packages.debian.org/sid/utils/unrar-free

**Comment by hadess** [comment]
This will be fixed in GNOME 3.26. Evince now has builtin support for RAR files.
